### ISSUE TITLE
Поддержка любого имени файла параметризации и шаблона в папке задачи

### ISSUE THREAD

**Issue by artyom-zolotarevskiy** [artyom-zolotarevskiy/taskgen-core#1]

**Comment by peryabov** [comment]
А какая функция клонирует данную папку? (Имею ввиду не все, а например, Q1)

**Comment by artyom-zolotarevskiy** [comment]
> А какая функция клонирует данную папку? (Имею ввиду не все, а например, Q1)

Функиця ``taskgen.gen_bank(n, folder)`` создает заданное число подстановок в заданой папке. Пример вызова функция в control_panel.ipynb для папки Q1:
``taskgen.gen_bank(n='15', folder='./bank/Q1')``

А вообще вопрос Вы задали не в том месте. Нужно было открыть новое "issue" с соответствующей темой с отметкой "help wanted".
