### ISSUE TITLE
make_variants не поддерживает произвольный уровень вложенности папок

### ISSUE THREAD

**Issue by peryabov** [artyom-zolotarevskiy/taskgen-core#16]
Получилось, что в папке Q1 создалось нужное количество клонов (по 10 шт кажой задачи)
Попытался из одно папки собрать вариант ,не получилось. 

![image](https://user-images.githubusercontent.com/126387648/221406292-8579b3f4-fe81-4403-9ee4-105e93668e20.png)

![image](https://user-images.githubusercontent.com/126387648/221406352-30b01921-33bb-45f6-b10a-683e638099ac.png)

**Comment by artyom-zolotarevskiy** [comment]
Действительно, сейчас функция make_variants не умеет создавать вариант из какой-либо подпапки банка. Только из всего банка, т.к. она сначала обходит папки Q1, ..., Q6, затем в каждой папке случайным образом выбирает тему, потом в каждой теме случайным образом выбирает задачу, потом в каждой задаче случайным образом выбирает подстановку. А если в качестве folder мы передадим папку задачи, то она просто не может найти нужную структуру /question/theme/task/substitution, поэтому и выдает ошибку. 

Это можно будет решить в новой версии ядра, разрешить любую вложенность папок в банке. Сейчас эта вложенность строго защита. Но тогда, если мы передадим make_variants папку Q1, а в ней лежит 10 тем, тогда в результате у нас получатся варианты с 10-ю задачами. Такое поведение будет нормальным? Или правило обхода стоит определить как-то по-другому?

**Comment by artyom-zolotarevskiy** [comment]
Пока вижу такое решение. В банке задачи могут располагаться с любым уровнем вложенности. make_variants может принимать любую папку из банка. По умолчанию файлы генерируются с определенным стандартным шаблоном, но этот шаблон можно переопределить, указав отдельно шаблон для экзамена, контрольной работы, проверочной, демо варианта, раздаточного листочка и т.д.

Учтем это в новой версии ядра генератора.
