### ISSUE TITLE
Проблема после установки новой версии ядра 0.3.6

### ISSUE THREAD

**Issue by peryabov** [artyom-zolotarevskiy/taskgen-core#24]
После установки последнй версии 0.3.6 выдает ошибку 
![image](https://user-images.githubusercontent.com/126387648/223708663-610dac4c-f8ac-4ab1-bad9-0a2b56d20fed.png)

**Comment by artyom-zolotarevskiy** [comment]
Последнее обновление ядра требует обновления и панели управления, но я забыл его перенести из ветки разработки (dev) в основную (main). Сейчас я это поправил, поэтому прошу еще раз скачать новую версию панели из этого репозитория - https://github.com/artyom-zolotarevskiy/taskgen.
