### ISSUE TITLE
Окружение Answer

### ISSUE THREAD

**Issue by peryabov** [artyom-zolotarevskiy/taskgen-core#32]
В окружении Answer не подствечивается подстановка VAR и E, как в окружении Solution при компиляции pdfLaTex
![image](https://user-images.githubusercontent.com/126387648/224331557-50f229e6-40fb-43c0-9797-0e277475014f.png)

![image](https://user-images.githubusercontent.com/126387648/224331722-81873a9a-0e43-4114-9c67-565ab6ae9a21.png)

Можно ли добавить подстветку в окружение Answer? Ведь это никак ни на что не влияет, а с точки зрения полноты визуализации будет лучше. Заранее спасибо.

**Comment by artyom-zolotarevskiy** [comment]
Попробуйте новую версию taskgen.sty - https://raw.githubusercontent.com/artyom-zolotarevskiy/taskgen/main/settings/taskgen.sty
