### ISSUE TITLE
MathJax no rendering \left( \right)

### ISSUE THREAD

**Issue by peryabov** [artyom-zolotarevskiy/taskgen-core#33]
MathJax не воспринимает окружение \left(  \right), а также \begin{equation*} \end{equation*}
![image](https://user-images.githubusercontent.com/126387648/224377409-4003ded6-4aea-42fa-95df-0ad6a992a580.png)

**Comment by artyom-zolotarevskiy** [comment]
MathJax должен поддерживать эти окружения. Полный список поддерживаемых макрокоманд приведен на этой странице - https://docs.mathjax.org/en/latest/input/tex/macros/index.html. 

Окружение `$$…$$` замените на `\[…\]`
