### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by peryabov** [artyom-zolotarevskiy/taskgen-core#5]
Ааа, понятно. Спасибо

**Comment by artyom-zolotarevskiy** [comment]
Вот здесь нужно указывать метку темы:
<img width="1345" alt="Снимок экрана 2023-02-26 в 13 30 27" src="https://user-images.githubusercontent.com/30539575/221405225-5ee85a36-b33a-40f6-9b67-3a76eb90d422.png">
